name: Python test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ] # scipy-1.11.1: Python version >= 3.9 required
    env:
      # Display must be available globally for linux to know where xvfb is
      DISPLAY: ":99.0"
      QT_SELECT: "qt6"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lxvfb ibegl1 libgl1-mesa-dev libxkbcommon-x11-0
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install .
      - name: Test with pytest
        run: |
          # export DISPLAY=:99
          # Xvfb :99 &
          python -m pytest tests/
